# -*- coding: utf-8 -*-
"""samurai

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdAQteyYPUCyi656OcziXxMFRojEGYWO
"""



upper = 10
lower = 20
hight = 5

print((upper + lower) * hight / 2)